# Generated by Django 6.0.3 on 2026-03-10 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=100)),
                ('original_photo', models.ImageField(upload_to='uploads/')),
                ('language', models.CharField(max_length=20)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('text_content', models.TextField()),
                ('scene_image', models.ImageField(upload_to='scenes/')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='story_app.story')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
    ]
